# This is a basic workflow to help you get started with Actions

name: Test Action

on:
  push:
    branches: [ master ]

jobs:
  use-action:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch data
      uses: ./dist
      with:
        url: 'https://fake-movie-database-api.herokuapp.com/api?s=batman'
      
    - name: list files
      run: |
        ls
        cd actions
        ls
